update.

diff --git a/.github/workflows/lib_data_auto_verify.yml b/.github/workflows/lib_data_auto_verify.yml
--- a/.github/workflows/lib_data_auto_verify.yml
+++ b/.github/workflows/lib_data_auto_verify.yml
@@ -142,108 +142,108 @@ jobs:
             --output text
           echo "Successfully sent command to create organization on instance: ${{ github.event.inputs.instance_id }}"
 
-      - name: Reconfigure Library Data Filename
-        run: |
-          aws ssm send-command \
-            --instance-ids "${{ github.event.inputs.instance_id }}" \
-            --document-name "AWS-RunShellScript" \
-            --parameters "commands=[\"sudo sed -i 's#FILE_NAME=.*\$#FILE_NAME=${{ github.event.inputs.lib_filename }}#' /root/git/TeamServerLibraryDataTest/playwright_dl_lib_data/lib_data.env\"]" \
-            --output text
-          echo "Successfully sent command to update file on instance: ${{ github.event.inputs.instance_id }}"
-
-      - name: Download Library Data via Playwright Container
-        id: library_data_download
-        run: |
-          aws ssm send-command \
-            --instance-ids "${{ github.event.inputs.instance_id }}" \
-            --document-name "AWS-RunShellScript" \
-            --parameters "commands=[\"sudo -i bash -c 'cd /root/git/TeamServerLibraryDataTest/playwright_dl_lib_data && docker-compose run --rm playwright_dl_lib_data'\"]" \
-            --output text
-          echo "Successfully sent command to download lib data file on instance: ${{ github.event.inputs.instance_id }}"
-
-      - name: Library Data Download Completion Check
-        id: check_for_lib_download
-        run: |
-          COMMAND_ID=$(aws ssm send-command \
-            --instance-ids "${{ github.event.inputs.instance_id }}" \
-            --document-name "AWS-RunShellScript" \
-            --parameters "commands=[\"sudo -i bash -c 'cd /root/git/TeamServerLibraryDataTest/playwright_dl_lib_data && ./md5sum_check.sh ${{ github.event.inputs.lib_filename }}'\"]" \
-            --output json | jq -r '.Command.CommandId')
-          echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_OUTPUT
-          echo "Successfully sent command to confirm Library Downloaded on instance: ${{ github.event.inputs.instance_id }}"
-
-      - name: Wait for Library Data Download Completion Check
-        id: wait_command_for_download
-        run: |
-          COMMAND_ID="${{ steps.check_for_lib_download.outputs.COMMAND_ID }}"
-          echo "Waiting for command ID: $COMMAND_ID to complete..."
-          while true; do
-            STATUS=$(aws ssm get-command-invocation \
-              --command-id "$COMMAND_ID" \
-              --instance-id "${{ github.event.inputs.instance_id }}" \
-              --output json | jq -r '.Status')
-            echo "Current Status: $STATUS"
-            if [[ "$STATUS" == "Success" || "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
-              echo "Command execution finished with status: $STATUS"
-              break
-            fi
-            sleep 30
-          done
-
-      - name: Unzip Library Data File
-        id: unzip_library_data
-        run: |
-          COMMAND_ID=$(aws ssm send-command \
-            --instance-ids "${{ github.event.inputs.instance_id }}" \
-            --document-name "AWS-RunShellScript" \
-            --parameters "commands=[\"sudo -i bash -c 'cd /root/git/TeamServerLibraryDataTest/eop && ./unzip.sh ${{ github.event.inputs.lib_filename }}'\"]" \
-            --output json | jq -r '.Command.CommandId')
-          echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_OUTPUT
-          echo "Successfully sent command to Unzip Library Data on instance: ${{ github.event.inputs.instance_id }}"
-
-      - name: Wait for Unzip Library Data File
-        id: wait_command_for_unzip
-        run: |
-          COMMAND_ID="${{ steps.unzip_library_data.outputs.COMMAND_ID }}"
-          echo "Waiting for command ID: $COMMAND_ID to complete..."
-          while true; do
-            INVOCATION=$(aws ssm get-command-invocation \
-              --command-id "$COMMAND_ID" \
-              --instance-id "${{ github.event.inputs.instance_id }}" \
-              --output json)
-            STATUS=$(echo "$INVOCATION" | jq -r '.Status')
-            echo "Current Status: $STATUS"
-            if [[ "$STATUS" == "Success" || "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
-              EXIT_CODE=$(echo "$INVOCATION" | jq -r '.CommandPlugins[0].Output.ExitCode')
-              echo "Command execution finished with status: $STATUS, Exit Code: $EXIT_CODE"
-              if [[ "$EXIT_CODE" -eq 0 ]]; then
-                echo "Command succeeded with exit code 0."
-              else
-                echo "Command finished successfully but with a non-zero exit code: $EXIT_CODE."
-                exit 1
-              fi
-              break
-            fi
-            sleep 30
-          done
-
-      - name: Restart TeamServer Container
-        id: teamserver_restart
-        run: |
-          aws ssm send-command \
-            --instance-ids "${{ github.event.inputs.instance_id }}" \
-            --document-name "AWS-RunShellScript" \
-            --parameters "commands=[\"sudo -i bash -c 'docker-compose -p eop restart teamserver'\"]" \
-            --output text
-          echo "Successfully sent command to Restart TeamServer on instance: ${{ github.event.inputs.instance_id }}"
-
-      - name: Log Monitor Startup
-        id: log_monitor_start
-        run: |
-          aws ssm send-command \
-            --instance-ids "${{ github.event.inputs.instance_id }}" \
-            --document-name "AWS-RunShellScript" \
-            --parameters "commands=[\"sudo -i bash -c 'cd /root/git/TeamServerLibraryDataTest/log_monitor && docker-compose run --rm log_monitor'\"]" \
-            --output text
-          echo "Successfully sent command to Start Log Monitor on instance: ${{ github.event.inputs.instance_id }}"
+#      - name: Reconfigure Library Data Filename
+#        run: |
+#          aws ssm send-command \
+#            --instance-ids "${{ github.event.inputs.instance_id }}" \
+#            --document-name "AWS-RunShellScript" \
+#            --parameters "commands=[\"sudo sed -i 's#FILE_NAME=.*\$#FILE_NAME=${{ github.event.inputs.lib_filename }}#' /root/git/TeamServerLibraryDataTest/playwright_dl_lib_data/lib_data.env\"]" \
+#            --output text
+#          echo "Successfully sent command to update file on instance: ${{ github.event.inputs.instance_id }}"
+#
+#      - name: Download Library Data via Playwright Container
+#        id: library_data_download
+#        run: |
+#          aws ssm send-command \
+#            --instance-ids "${{ github.event.inputs.instance_id }}" \
+#            --document-name "AWS-RunShellScript" \
+#            --parameters "commands=[\"sudo -i bash -c 'cd /root/git/TeamServerLibraryDataTest/playwright_dl_lib_data && docker-compose run --rm playwright_dl_lib_data'\"]" \
+#            --output text
+#          echo "Successfully sent command to download lib data file on instance: ${{ github.event.inputs.instance_id }}"
+#
+#      - name: Library Data Download Completion Check
+#        id: check_for_lib_download
+#        run: |
+#          COMMAND_ID=$(aws ssm send-command \
+#            --instance-ids "${{ github.event.inputs.instance_id }}" \
+#            --document-name "AWS-RunShellScript" \
+#            --parameters "commands=[\"sudo -i bash -c 'cd /root/git/TeamServerLibraryDataTest/playwright_dl_lib_data && ./md5sum_check.sh ${{ github.event.inputs.lib_filename }}'\"]" \
+#            --output json | jq -r '.Command.CommandId')
+#          echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_OUTPUT
+#          echo "Successfully sent command to confirm Library Downloaded on instance: ${{ github.event.inputs.instance_id }}"
+#
+#      - name: Wait for Library Data Download Completion Check
+#        id: wait_command_for_download
+#        run: |
+#          COMMAND_ID="${{ steps.check_for_lib_download.outputs.COMMAND_ID }}"
+#          echo "Waiting for command ID: $COMMAND_ID to complete..."
+#          while true; do
+#            STATUS=$(aws ssm get-command-invocation \
+#              --command-id "$COMMAND_ID" \
+#              --instance-id "${{ github.event.inputs.instance_id }}" \
+#              --output json | jq -r '.Status')
+#            echo "Current Status: $STATUS"
+#            if [[ "$STATUS" == "Success" || "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
+#              echo "Command execution finished with status: $STATUS"
+#              break
+#            fi
+#            sleep 30
+#          done
+#
+#      - name: Unzip Library Data File
+#        id: unzip_library_data
+#        run: |
+#          COMMAND_ID=$(aws ssm send-command \
+#            --instance-ids "${{ github.event.inputs.instance_id }}" \
+#            --document-name "AWS-RunShellScript" \
+#            --parameters "commands=[\"sudo -i bash -c 'cd /root/git/TeamServerLibraryDataTest/eop && ./unzip.sh ${{ github.event.inputs.lib_filename }}'\"]" \
+#            --output json | jq -r '.Command.CommandId')
+#          echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_OUTPUT
+#          echo "Successfully sent command to Unzip Library Data on instance: ${{ github.event.inputs.instance_id }}"
+#
+#      - name: Wait for Unzip Library Data File
+#        id: wait_command_for_unzip
+#        run: |
+#          COMMAND_ID="${{ steps.unzip_library_data.outputs.COMMAND_ID }}"
+#          echo "Waiting for command ID: $COMMAND_ID to complete..."
+#          while true; do
+#            INVOCATION=$(aws ssm get-command-invocation \
+#              --command-id "$COMMAND_ID" \
+#              --instance-id "${{ github.event.inputs.instance_id }}" \
+#              --output json)
+#            STATUS=$(echo "$INVOCATION" | jq -r '.Status')
+#            echo "Current Status: $STATUS"
+#            if [[ "$STATUS" == "Success" || "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
+#              EXIT_CODE=$(echo "$INVOCATION" | jq -r '.CommandPlugins[0].Output.ExitCode')
+#              echo "Command execution finished with status: $STATUS, Exit Code: $EXIT_CODE"
+#              if [[ "$EXIT_CODE" -eq 0 ]]; then
+#                echo "Command succeeded with exit code 0."
+#              else
+#                echo "Command finished successfully but with a non-zero exit code: $EXIT_CODE."
+#                exit 1
+#              fi
+#              break
+#            fi
+#            sleep 30
+#          done
+#
+#      - name: Restart TeamServer Container
+#        id: teamserver_restart
+#        run: |
+#          aws ssm send-command \
+#            --instance-ids "${{ github.event.inputs.instance_id }}" \
+#            --document-name "AWS-RunShellScript" \
+#            --parameters "commands=[\"sudo -i bash -c 'docker-compose -p eop restart teamserver'\"]" \
+#            --output text
+#          echo "Successfully sent command to Restart TeamServer on instance: ${{ github.event.inputs.instance_id }}"
+#
+#      - name: Log Monitor Startup
+#        id: log_monitor_start
+#        run: |
+#          aws ssm send-command \
+#            --instance-ids "${{ github.event.inputs.instance_id }}" \
+#            --document-name "AWS-RunShellScript" \
+#            --parameters "commands=[\"sudo -i bash -c 'cd /root/git/TeamServerLibraryDataTest/log_monitor && docker-compose run --rm log_monitor'\"]" \
+#            --output text
+#          echo "Successfully sent command to Start Log Monitor on instance: ${{ github.event.inputs.instance_id }}"
 
